// Sci-Fi Space Shooter Soundtrack
// Evolving generative soundtrack with drums, bass, and lead
export default {
    name: 'Demo - Sci-Fi Shooter',
    factory: true,
    state: {
        modules: [
            { type: 'clk', instanceId: 'clock', row: 1 },
            { type: 'div', instanceId: 'divider', row: 1 },
            { type: 'euclid', instanceId: 'kickPattern', row: 1 },
            { type: 'euclid', instanceId: 'hatPattern', row: 1 },
            { type: 'kick', instanceId: 'kick', row: 1 },
            { type: 'hat', instanceId: 'hat', row: 1 },
            { type: 'snare', instanceId: 'snare', row: 1 },
            { type: 'turing', instanceId: 'turingBass', row: 1 },
            { type: 'quant', instanceId: 'quantBass', row: 1 },
            { type: 'vco', instanceId: 'vcoBass', row: 1 },
            { type: 'vcf', instanceId: 'vcfBass', row: 1 },
            { type: 'adsr', instanceId: 'adsrBass', row: 1 },
            { type: 'vca', instanceId: 'vcaBass', row: 1 },
            { type: 'turing', instanceId: 'turingLead', row: 1 },
            { type: 'quant', instanceId: 'quantLead', row: 1 },
            { type: 'vco', instanceId: 'vcoLead', row: 1 },
            { type: 'fold', instanceId: 'foldLead', row: 1 },
            { type: 'adsr', instanceId: 'adsrLead', row: 1 },
            { type: 'nse', instanceId: 'noise', row: 1 },
            { type: 'vca', instanceId: 'vcaLead', row: 2 },
            { type: 'mix', instanceId: 'drumMix', row: 2 },
            { type: 'mix', instanceId: 'synthMix', row: 2 },
            { type: 'dly', instanceId: 'delay', row: 2 },
            { type: 'verb', instanceId: 'reverb', row: 2 },
            { type: 'mix', instanceId: 'masterMix', row: 2 },
            { type: 'out', instanceId: 'output', row: 2 }
        ],
        knobs: {
            clock: { rate: 0.29333333333333333 },
            divider: { rate1: 0.5333333333333333, rate2: 0.5 },
            kickPattern: { length: 16, hits: 4, rotate: 0 },
            hatPattern: { length: 16, hits: 6, rotate: 0 },
            kick: { pitch: 0.3, decay: 0.5, tone: 0.2, click: 0 },
            hat: { decay: 0.25, sizzle: 0.5, blend: 0.5 },
            snare: { snap: 0.19333333333333336, decay: 0.20666666666666672, pitch: 0.24666666666666665 },
            turingBass: { lock: 0.85, scale: 0.2, length: 5 },
            quantBass: { scale: 2, octave: -2, semitone: 0 },
            vcoBass: { coarse: 0.6833333333333333, fine: -2.4000000000000004, glide: 14.666666666666671 },
            vcfBass: { cutoff: 0.49999999999999994, resonance: 0.11333333333333336 },
            adsrBass: { attack: 0.3, decay: 0.4, sustain: 0.5, release: 0.62 },
            vcaBass: { ch1Gain: 0.7, ch2Gain: 0.8 },
            turingLead: { lock: 0.8, scale: 0.2, length: 5 },
            quantLead: { scale: 2, octave: -1, semitone: 0 },
            vcoLead: { coarse: 0.3, fine: 0.56, glide: 14 },
            foldLead: { fold: 0.3333333333333333, sym: 0.17333333333333328 },
            adsrLead: { attack: 0.3, decay: 0.4, sustain: 0.6, release: 0.5 },
            noise: { rate: 0.4866666666666667 },
            vcaLead: { ch1Gain: 0.6, ch2Gain: 0.8 },
            drumMix: { lvl1: 0.7, lvl2: 0.4, lvl3: 0.21333333333333332, lvl4: 0 },
            synthMix: { lvl1: 0.6, lvl2: 0.5, lvl3: 0.039999999999999994, lvl4: 0 },
            delay: { time: 0.35, feedback: 0.35, mix: 0.3 },
            reverb: { time: 0.5, damp: 0.5, mix: 0.35 },
            masterMix: { lvl1: 0.6, lvl2: 0.64, lvl3: 0, lvl4: 0 },
            output: { volume: 0.8 }
        },
        switches: {
            clock: { pause: false },
            noise: { vcaMode: false }
        },
        buttons: {},
        cables: [
            { fromModule: 'clock', fromPort: 'clock', toModule: 'divider', toPort: 'clock' },
            { fromModule: 'divider', fromPort: 'out1', toModule: 'kickPattern', toPort: 'clock' },
            { fromModule: 'clock', fromPort: 'clock', toModule: 'hatPattern', toPort: 'clock' },
            { fromModule: 'divider', fromPort: 'out2', toModule: 'snare', toPort: 'trigger' },
            { fromModule: 'kickPattern', fromPort: 'trig', toModule: 'kick', toPort: 'trigger' },
            { fromModule: 'kick', fromPort: 'out', toModule: 'drumMix', toPort: 'in1' },
            { fromModule: 'hat', fromPort: 'out', toModule: 'drumMix', toPort: 'in2' },
            { fromModule: 'snare', fromPort: 'out', toModule: 'drumMix', toPort: 'in3' },
            { fromModule: 'divider', fromPort: 'out1', toModule: 'turingBass', toPort: 'clock' },
            { fromModule: 'turingBass', fromPort: 'cv', toModule: 'quantBass', toPort: 'cv' },
            { fromModule: 'quantBass', fromPort: 'cv', toModule: 'vcoBass', toPort: 'vOct' },
            { fromModule: 'turingBass', fromPort: 'pulse', toModule: 'adsrBass', toPort: 'gate' },
            { fromModule: 'vcoBass', fromPort: 'pulse', toModule: 'vcfBass', toPort: 'audio' },
            { fromModule: 'vcfBass', fromPort: 'lpf', toModule: 'vcaBass', toPort: 'ch1In' },
            { fromModule: 'adsrBass', fromPort: 'env', toModule: 'vcaBass', toPort: 'ch1CV' },
            { fromModule: 'clock', fromPort: 'clock', toModule: 'turingLead', toPort: 'clock' },
            { fromModule: 'turingLead', fromPort: 'cv', toModule: 'quantLead', toPort: 'cv' },
            { fromModule: 'quantLead', fromPort: 'cv', toModule: 'vcoLead', toPort: 'vOct' },
            { fromModule: 'turingLead', fromPort: 'pulse', toModule: 'adsrLead', toPort: 'gate' },
            { fromModule: 'vcoLead', fromPort: 'ramp', toModule: 'foldLead', toPort: 'audio' },
            { fromModule: 'foldLead', fromPort: 'out', toModule: 'vcaLead', toPort: 'ch1In' },
            { fromModule: 'adsrLead', fromPort: 'env', toModule: 'vcaLead', toPort: 'ch1CV' },
            { fromModule: 'vcaBass', fromPort: 'ch1Out', toModule: 'synthMix', toPort: 'in1' },
            { fromModule: 'vcaLead', fromPort: 'ch1Out', toModule: 'synthMix', toPort: 'in2' },
            { fromModule: 'noise', fromPort: 'noise', toModule: 'synthMix', toPort: 'in3' },
            { fromModule: 'synthMix', fromPort: 'out', toModule: 'delay', toPort: 'audio' },
            { fromModule: 'delay', fromPort: 'out', toModule: 'reverb', toPort: 'audioL' },
            { fromModule: 'delay', fromPort: 'out', toModule: 'reverb', toPort: 'audioR' },
            { fromModule: 'drumMix', fromPort: 'out', toModule: 'masterMix', toPort: 'in1' },
            { fromModule: 'reverb', fromPort: 'outL', toModule: 'masterMix', toPort: 'in2' },
            { fromModule: 'masterMix', fromPort: 'out', toModule: 'output', toPort: 'L' },
            { fromModule: 'masterMix', fromPort: 'out', toModule: 'output', toPort: 'R' }
        ]
    }
};
